spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: "localhost"
      port: 6379
      database: 0
      password: "xchange_password"

jwt:
  secret-key: ${JWT_SK}

coingecko:
  api-key: ${COINGECKO_KEY}